title: YoWASP
description: Unofficial WebAssembly-based packages for Yosys, nextpnr, and more
affiliation: A <a href="https://www.fossi-foundation.org/">FOSSi Foundation</a> project
github:
  repository_url: https://github.com/YoWASP
  owner_name: whitequark
  owner_url: mailto:whitequark@whitequark.org

markdown: kramdown
theme: jekyll-theme-slate
