title: YoWASP
description: Unofficial WebAssembly-based packages for Yosys, nextpnr, and more
github:
  repository_url: https://github.com/YoWASP
  owner_name: whitequark
  owner_url: mailto:whitequark@whitequark.org
  is_project_page: true # show footer

markdown: kramdown
theme: jekyll-theme-slate
